"""init schema

Revision ID: 438be7143c16
Revises: 
Create Date: 2026-02-09 15:26:05.821503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438be7143c16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clock_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_in_ip', sa.String(length=100), nullable=True),
    sa.Column('clock_in_ua', sa.String(length=300), nullable=True),
    sa.Column('clock_out_ip', sa.String(length=100), nullable=True),
    sa.Column('clock_out_ua', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_user_id'), 'shifts', ['user_id'], unique=False)
    op.create_index('ix_shifts_user_open_unique', 'shifts', ['user_id'], unique=True, sqlite_where=sa.text('clock_out_at IS NULL'), postgresql_where=sa.text('clock_out_at IS NULL'))
    op.create_table('breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_ip', sa.String(length=100), nullable=True),
    sa.Column('start_ua', sa.String(length=300), nullable=True),
    sa.Column('end_ip', sa.String(length=100), nullable=True),
    sa.Column('end_ua', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breaks_shift_id'), 'breaks', ['shift_id'], unique=False)
    op.create_index('ix_breaks_shift_open_unique', 'breaks', ['shift_id'], unique=True, sqlite_where=sa.text('end_at IS NULL'), postgresql_where=sa.text('end_at IS NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_breaks_shift_open_unique', table_name='breaks')
    op.drop_index(op.f('ix_breaks_shift_id'), table_name='breaks')
    op.drop_table('breaks')
    op.drop_index('ix_shifts_user_open_unique', table_name='shifts')
    op.drop_index(op.f('ix_shifts_user_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
